add change close and lift NTI to use model binding
DFE-Digital/amsd-casework pull request #829
Opened 2023-03-30 12:14 UTC by elielijah321

**What is the change?**
Change the lift and close page so the data validation message appears on the page

**Why do we need the change?**
Consistencty amongst error messages

**What is the impact?**
Medium - Should be checked over by @FahadDarw 

**Azure DevOps Ticket**
[125223](https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_sprints/taskboard/Concerns%20Casework/Academies-and-Free-Schools-SIP/CC/CC%20-%20Iteration%2040?workitem=125223)

2023-03-30 15:37 UTC, mikestock-nimble requested changes
Just a small query on a text change

2023-03-30 15:37 UTC, mikestock-nimble commented on ConcernsCaseWork/ConcernsCaseWork/Pages/Case/Management/Action/Nti/Close.cshtml
> +                        This action cannot be reopened. Check the details are correct before lifting
QUERY:

Should this still be closing?

2023-03-31 08:50 UTC, mikestock-nimble requested changes

2023-03-31 08:50 UTC, mikestock-nimble commented on ConcernsCaseWork/ConcernsCaseWork/Pages/Case/Management/Action/Nti/EditableNTIPageModel.cs
> +public class EditableNTIPageModel : AbstractPageModel
SUGGESTION: I would call this CloseNtiBasePage

Its a page that is used by all close states of an NTI

2023-04-03 09:35 UTC, merged

2023-04-03 09:57 UTC, FahadDarw commented
Happy with Cypress changes.